### ISSUE TITLE
Calendar invite gives 404

### ISSUE THREAD

**Issue by habi** [COBA-NIH/i2kconference#1]
https://coba-nih.github.io/assets/calendar-invite.ics does not work.

**Comment by habi** [comment]
I don't know enough about Jekyll to change to the correct path/code/link at https://github.com/COBA-NIH/i2kconference/blob/f7490d2ae8312f649e460063b12ed34c02863594/_layouts/default.html#L27 and submit a PR, unfortunately.

**Comment by smgriffin2** [comment]
Thanks for catching this! I've disabled this feature while we find a work around. It looks like .ics files may not play nicely with GitHub pages from a look at google-- was working fine on a local version of the site.

**Comment by habi** [comment]
I'm looking forward to the conference anyways :)
